### ISSUE TITLE
Merge pull fail

### ISSUE THREAD

**Issue by Accelium** [FZM-Technologies/Aquadroid#18]
[![C/C++ CI](https://github.com/FZM-Technologies/Aquadroid/actions/workflows/c-cpp.yml/badge.svg)](https://github.com/FZM-Technologies/Aquadroid/actions/workflows/c-cpp.yml)

**Comment by Faimue** [comment]
I'm processing the report now.
Should take a few mins

**Comment by Faimue** [comment]
@Accelium are you there?

**Comment by Accelium** [comment]
Yes

**Comment by Faimue** [comment]
#include <stdio.h>

int main() {
  int login;
  printf("Welcome to Aquadroid");
  printf("This is the customThemes strand");
  printf("Loading");
  return 0;
  if  (login = 0)  {
   printf("you are not logged in");
   printf("login");
int login = 1
  }
}

**Comment by Faimue** [comment]
```
Task complete. 

Destroying issue and replacing buomd
```
