### ISSUE TITLE
Rerun check failure 

### ISSUE THREAD

**Issue by Accelium** [FZM-Technologies/Aquadroid#21]
https://github.com/FZM-Technologies/Aquadroid/commit/24a21acf864d40eeb44d148e2107c5543c8e8568/checks?check_suite_id=11971464913

**Comment by Accelium** [comment]
Rerun check failed

**Comment by Faimue** [comment]
@Accelium what do you suggest?

**Comment by Accelium** [comment]
If something is wrong with the code rewrite it

**Comment by Faimue** [comment]
I think I've got some more re-writing to do
